### ISSUE TITLE
When i add library to my RN project this changes the container colors

### ISSUE THREAD

**Issue by AgustinJN** [BlackBoxVision/react-native-mercadopago-px#26] opened 2020-11-05 13:03 UTC
**Describe the bug**
When i add library to my RN project this changes the container colors by gray

**To Reproduce**
1. Install library
2. Start Payment
3. See error

**Screenshots**
![Captura](https://user-images.githubusercontent.com/72032144/98244075-9b194700-1f4d-11eb-9d5c-5defb3d367ff.PNG)

**Smartphone (please complete the following information):**
 - Device: Pixel_3a_API_30_x86
 - OS: Android 11.0
 - Version 30 apk

**Comment by manutuero** [comment] 2020-11-06 10:25
Hi @AgustinJN 

Two questions: 
- Which react-native version are you using? 
- Can you give us developer access to some repo to see the android config of your project?

In our example we test the behavior and works normally.

**Comment by JonatanSalas** [comment] 2020-11-10 23:19
@AgustinJN we're not able to reproduce the following issue, maybe it's something related to a library that gets updated and it's messing up. Our library doesn't include styles because it only exposes an adapter to native code that doesn't runs in JS land. 

Closing this issue since it isn't related to library itself.

**Closed by JonatanSalas** 2020-11-10 23:19 UTC

**Comment by JonatanSalas** [comment] 2020-11-14 12:49
@AgustinJN we've added a section explaining how to fix this issue:

https://github.com/BlackBoxVision/react-native-mercadopago-px#in-android-background-color-turns-gray

We're going to review, but it isn't a priority in our backlog, since we've more things to get done.
